### ISSUE TITLE
Canvas: cannot delete a component definition when deployment status is `In-Progress-CompCon`

### ISSUE THREAD

**Issue by ycardon-pro** [tmforum-oda/oda-canvas-charts#34]
## Long story short

When a component deployment fails and status is `In-Progress-CompCon`, it's not possible to delete the component definition.

## workaround

edit the component definition and remove the finalizers section

```yaml
apiVersion: oda.tmforum.org/v1alpha3
kind: component
metadata:
  ...
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
```
